# This compose file is mainly used for development.
# Write your own base on the Run `live-dl` with Docker Compose section in readme

version: '3'

x-defaults: &defaults
  build:
    context: .
    dockerfile: Dockerfile
  image: sparanoid/live-dl:local
  restart: always
  environment:
    - _PARAM_BASE_DIR=testdir
  volumes:
    - .:/app

services:
  # testlive:
  #   <<: *defaults
  #   command: https://www.youtube.com/watch?v=rQL0YJE04CY --debug

  # uruharushia:
  #   <<: *defaults
  #   command: https://www.youtube.com/channel/UCl_gCybOJRIgOXw6Qb4qJzQ --debug

  minatoaqua:
    <<: *defaults
    command: https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg --debug
